SCREEN_TITLE = "Survivor Game"

SPRITE_SCALING = 0.25
SPRITE_SIZE = 32

GRID_WIDTH = 30
GRID_HEIGHT = 20
SPRITE_SPEED = 1

PLAYER_HEALTH = 5

MAP_WALL = 'W'  # Wall
MAP_WALL_T = 'WT'  # Wall
MAP_OBSTACLE = 'O'  # Obstacle
MAP_OBSTACLE2 = 'O2'  # Obstacle
MAP_OBSTACLE3 = 'O3'  # Obstacle
MAP_EMPTY = 'E'  # Empty
MAP_AGENT = 'A'  # Agent
MAP_ENEMY = 'EN1'  # Enemy
MAP_ENEMY2 = 'EN2'  # Enemy
